# Generated by Django 3.1.7 on 2021-03-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_auto_20210323_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('par_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'participant',
                'managed': False,
            },
        ),
    ]
