# Generated by Django 3.1.7 on 2021-03-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_participant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={},
        ),
    ]
