# Generated by Django 3.1.7 on 2021-03-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_auto_20210323_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
