# Generated by Django 3.1.7 on 2021-03-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_auto_20210324_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='num_of_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='num_of_upvotes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
