# Generated by Django 3.1.7 on 2021-03-23 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_participant'),
        ('user', '0002_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.event')),
                ('par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.participant')),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
