# Generated by Django 3.1.7 on 2021-03-24 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_auto_20210324_1010'),
        ('administrator', '0003_auto_20210324_1010'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
